- name: "Install rsync to remote server"
  become: true
  apt:
    name: rsync
    state: present
  register: apt_command_output
- debug: 
    var: apt_command_output
    verbosity: 3

- name: "Copying backend files to remote web server using syncronization"
  synchronize:
    src:  /root/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz
  register: check_copy_error
- debug: 
    var: check_copy_error
    verbosity: 3

- name: "Check for tar file"
  become: true
  command: ls -larth /home/ubuntu/


- name: Creates directory
  file:
    path:  /home/ubuntu/udapeople-app
    state: directory

- name: Unarchive a file that is already on the remote machine.
  unarchive:
    src: /home/ubuntu/artifact.tar.gz
    dest: /home/ubuntu/udapeople-app
    remote_src: yes

- name: "delete anything that might already be running"
  become: true
  command: pm2 delete all
  ignore_errors: true
  
- name: "start server"
  become: true
  args:
    chdir: /home/ubuntu/udapeople-app
  command: "{{ item }}"
  loop:
    - 
    - pwd
    - chmod a+rwx /home/ubuntu/udapeople-app
    - cd /home/ubuntu/udapeople-app
    - npm install
    - pm2 stop default
    - pm2 start npm -- start
  register: check_npm_start_error
- debug: 
    var : check_npm_start_error
    verbosity: 3
